// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://raqeuvseulcnebhwcjay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhcWV1dnNldWxjbmViaHdjamF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5ODA5MjYsImV4cCI6MjA2NjU1NjkyNn0.crCFsQ6vyOXrBhpxDA9--wx4mi1X1uH62_2lFqUHTxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);